### ISSUE TITLE
Missing export of iosTransitionAnimation

### ISSUE THREAD

**Issue by thomasdondorf** [rdlabo-team/ionic-theme-ios26#81]
Looks like the function `iosTransitionAnimation` in version 2.0.0 is not actually exported.

```
Module '"@rdlabo/ionic-theme-ios26"' has no exported member 'iosTransitionAnimation'.
```

**Comment by rdlabo** [comment]
Sorry about that — it was completely my mistake.
Thanks for pointing it out. I’ve fixed it, so please try it again in v2.0.1!

**Comment by thomasdondorf** [comment]
Thanks for the quick reply!

Unfortunately, it's still broken for me:

```
Could not resolve "../focus-controller "

    ../../node_modules/@rdlabo/ionic-theme-ios26/dist/transition/index.js:4:38:
      4 │ import { createFocusController } from '../focus-controller ';
```

Turns out you have a typo in your directory name:

The directory `focus-controller` is actually named `focus-controller ` (with a leading space).

And then it's referenced here, but looks like my Node.js does not like imports ending with a space.

https://github.com/rdlabo-team/ionic-theme-ios26/blob/995ce8aa127f910af3cfa046b1beb2fb1a4866c0/src/transition/index.ts#L7

Again, notice the space after `focus-controller`.

**Comment by rdlabo** [comment]
@thomasdondorf I didn't notice at all. It might be a difference between Windows and Mac.

I've released a fixed version at https://github.com/rdlabo-team/ionic-theme-ios26/releases/tag/v2.0.2, so please try it out.

**Comment by thomasdondorf** [comment]
Now it's working for me! Thank you!
